[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        14
    outer.right =      20

[mode.main.binding]
   alt-h = 'focus left'
   alt-j = 'focus down'
   alt-k = 'focus up'
   alt-l = 'focus right'

   alt-shift-h = 'move left'
   alt-shift-j = 'move down'
   alt-shift-k = 'move up'
   alt-shift-l = 'move right'

   alt-shift-f = 'layout floating tiling'
   alt-f = 'fullscreen'

   alt-1 = 'workspace web'
   alt-2 = 'workspace term'
   alt-3 = 'workspace notes'
   alt-4 = 'workspace teams'
   alt-5 = 'workspace mail'
   alt-6 = 'workspace music'
   alt-7 = 'workspace misc_1'
   alt-8 = 'workspace misc_2'
   alt-9 = 'workspace misc_3'

   alt-shift-1 = ['move-node-to-workspace web', 'workspace web']
   alt-shift-2 = ['move-node-to-workspace term', 'workspace term']
   alt-shift-3 = ['move-node-to-workspace notes', 'workspace notes']
   alt-shift-4 = ['move-node-to-workspace teams', 'workspace teams']
   alt-shift-5 = ['move-node-to-workspace mail', 'workspace mail']
   alt-shift-6 = ['move-node-to-workspace music', 'workspace music']
   alt-shift-7 = ['move-node-to-workspace misc_1', 'workspace misc_1']
   alt-shift-8 = ['move-node-to-workspace misc_2', 'workspace misc_2']
   alt-shift-9 = ['move-node-to-workspace misc_3', 'workspace misc_3']

[[on-window-detected]]
  if.app-name-regex-substring = 'simulator'
  run = 'layout tiling'

[[on-window-detected]]
  if.app-name-regex-substring = 'finder'
  run = 'layout floating'

[[on-window-detected]]
  if.app-name-regex-substring = 'safari'
  run = ['move-node-to-workspace web', 'focus-back-and-forth']

[[on-window-detected]]
  if.app-name-regex-substring = 'chrome'
  run = ['move-node-to-workspace web', 'focus-back-and-forth']

[[on-window-detected]]
  if.app-name-regex-substring = 'ghostty'
  run = ['move-node-to-workspace term', 'focus-back-and-forth']

[[on-window-detected]]
  if.app-name-regex-substring = 'teams'
  run = ['move-node-to-workspace teams', 'focus-back-and-forth']

[[on-window-detected]]
  if.app-name-regex-substring = 'mail'
  run = ['move-node-to-workspace mail', 'focus-back-and-forth']
